gmail:
  # gmail에서 불러올 시작 날짜 (값이 없는 경우 2025/01/10)
  start_date:
  # gmail에서 불러올 끝 날짜 (값이 없는 경우 오늘 날짜)
  end_date:
  # gmail에서 불러올 메일 최대 개수
  max_mails: 20

evaluation:
  # TODO: 개별 요약 설정 통합 검토
  summary: False
  classification:
    # 분류 평가 여부
    do_eval: False
    # 기준 모델이 생성한 데이터 필터 여부
    do_manual_filter: False
    # Consistency 평가 용 반복 추론 횟수 설정
    inference: 5
