# CSV 파일 경로
json_file: "example_data.json"

# 계산할 메트릭 목록
metrics:
  - rouge
  - bert
  - g-eval

# BERTScore에서 사용할 모델
bert_model: "distilbert-base-uncased"

# G-EVAL setting
g_eval:
  openai_model: "gpt-4"
  prompts:
    consistency: "prompt/template/g_eval/con_summary.txt"
    coherence: "prompt/template/g_eval/coh_summary.txt"
    fluency: "prompt/template/g_eval/flu_summary.txt"
    relevance: "prompt/template/g_eval/rel_summary.txt"
